version: '2'

services:
  postgres:
      container_name: krappelaarnio_pg
      image: sameersbn/postgresql:9.6-2
      ports:
        - 5434:5432
      environment:
        DB_NAME: krappelaarnio, krappetesti
        DB_USER: krappe
        DB_PASS: laarnio
      volumes:
        - ~/docker/pgdata:/var/lib/postgresql/data
